import LegalLayout, { LegalSection } from "./LegalLayout";
export default function PrivacyPolicy(){return <LegalLayout eyebrow="Your information" title="Privacy Policy" intro="This draft explains the types of information G3 Store may process to create accounts, fulfil orders, provide membership features, process payments and support customers. Review it for compliance with the laws that apply to your business before publishing as a final policy.">
<LegalSection title="Information we collect"><p>G3 Store may collect your name, email address, phone number, delivery address, account credentials in protected form, order details, membership information, referral information and payment references needed to operate the service.</p></LegalSection>
<LegalSection title="How we use information"><p>Information is used to create and secure accounts, process and fulfil orders, manage stock, provide membership features, verify payments, communicate about orders, prevent abuse and improve the store.</p></LegalSection>
<LegalSection title="Payments"><p>G3 Store does not need to store your Paystack card details. Payment processing is handled by the payment provider. Bank-transfer records may include the order and transaction information needed to verify payment.</p></LegalSection>
<LegalSection title="Sharing"><p>Information may be shared with service providers that are necessary to operate the store, such as payment, hosting, database, image-storage and delivery services, only as appropriate for the service.</p></LegalSection>
<LegalSection title="Security"><p>Passwords should be stored using secure hashing, administrator functions are protected by authorization checks, and payment webhooks are verified before changing payment status. No online system can guarantee absolute security.</p></LegalSection>
<LegalSection title="Your choices"><p>Customers can contact G3 Store through the published support channel to ask about their account information, corrections or privacy questions. Applicable legal rights and retention requirements may affect what can be deleted.</p></LegalSection>
</LegalLayout>}
