import LegalLayout, { LegalSection } from "./LegalLayout";
export default function Terms(){return <LegalLayout eyebrow="G3 Store agreement" title="Terms & Conditions" intro="These terms explain the rules for using G3 Store, placing orders, making payments and using G3 Lounge membership features. They should be reviewed and adapted with qualified legal advice before being treated as a final legal contract.">
<LegalSection title="1. Using G3 Store"><p>G3 Store provides a catalogue of everyday products, gifts, personal-care items, accessories and related experiences. By creating an account or placing an order, you agree to provide accurate information and to use the service lawfully.</p></LegalSection>
<LegalSection title="2. Accounts"><p>You are responsible for keeping your account information accurate and for protecting your login credentials. Administrator access is reserved for authorized G3 Store staff and is not available through ordinary customer registration.</p></LegalSection>
<LegalSection title="3. Products and availability"><p>Products, prices, descriptions, images and stock can change. A product shown in the catalogue is subject to availability. G3 Store may correct genuine listing errors or remove a product that is unavailable.</p></LegalSection>
<LegalSection title="4. Orders"><p>An order is submitted when the checkout process is completed successfully. G3 Store may contact you to confirm delivery information or payment details. The backend records the order, its items, price and payment status so the order can be fulfilled accurately.</p></LegalSection>
<LegalSection title="5. Payments"><p>Customers may be offered Paystack or bank transfer. Paystack transactions are processed through Paystack. Bank-transfer orders remain pending until G3 verifies the transfer according to its payment procedure.</p></LegalSection>
<LegalSection title="6. Membership"><p>G3 Lounge may provide Guest, Member and Premier access levels. Membership benefits and product access are controlled by the membership rules displayed by G3 Store and may change for future orders.</p></LegalSection>
<LegalSection title="7. Prohibited use"><p>Do not misuse the store, attempt to bypass membership access, interfere with the service, submit fraudulent payment information, or access administrator functions without authorization.</p></LegalSection>
<LegalSection title="8. Changes and contact"><p>G3 Store may update these terms as the service develops. The current version published in the application is the version presented to customers. For support, use the contact details shown in the application.</p></LegalSection>
</LegalLayout>}
